#!/usr/bin/env python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

"""
    This file is part of Torrent Search.
    
    Torrent Search is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Torrent Search is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os

PATH = os.path.split(__file__)[0]

if __name__ == "__main__":
    os.system('python3 "%s" --share-dir "%s"' % (os.path.join(PATH, "gen-manpages"), os.path.join(PATH, "share")))
    os.system('python3 "%s" --share-dir "%s"' % (os.path.join(PATH, "package-manpages"), os.path.join(PATH, "share")))
    os.system('python3 "%s" --share-dir "%s"' % (os.path.join(PATH, "update-locales"), os.path.join(PATH, "share")))
